-- Compatibility note:
-- Database schema is now versioned in migrations/.
-- The initial schema lives in migrations/0001_init.sql and is applied by
-- Database.initialize() through the schema_migrations table.
